# Generated by Django 5.1.2 on 2024-10-15 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
